[package]
name = "risc0-r0vm"
description = "RISC Zero zero-knowledge VM executable"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = "1.0"
bytemuck = "1.12"
clap = { version = "4.0", features = ["derive"] }
env_logger = "0.10"
risc0-zkvm = { workspace = true, features = ["default", "binfmt"] }

[dev-dependencies]
anyhow = "1.0"
assert_cmd = "2.0"
assert_fs = "1.0"
risc0-zkvm-methods = { path = "../zkvm/methods" }
risc0-zkvm-platform = { workspace = true }

[features]
cuda = ["risc0-zkvm/cuda"]
default = []
metal = ["risc0-zkvm/metal"]
profiler = ["risc0-zkvm/profiler"]
