[package]
name = "risc0-zkvm-platform"
description = "RISC Zero zero-knowledge VM"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

# This crate is a potential dependency of the rust standard library.
# As such, it should not depend on anything the rust standard library
# doesn't.
#
# Also, it needs special trickery to work with the rust standard
# library build scripts; see rustc-std-workspace-core/README.md in the
# rust tree for details.
[dependencies]
compiler_builtins = { version = "0.1", optional = true }
core = { optional = true, package = "rustc-std-workspace-core", version = "1.0.0" }

[features]
default = []
rustc-dep-of-std = ["core", "compiler_builtins"]
