[package]
name = "zkevm-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
env_logger = "0.10"
ethers-core = "2.0"
ethers-providers = "2.0"
log = "0.4"
risc0-zkvm = { path = "../../risc0/zkvm" }
serde = "1.0"
tempfile = "3.5"
tokio = "1.23"
zkevm-core = { path = "core", features = ["ethers"] }
zkevm-methods = { path = "methods" }

[features]
cuda = ["risc0-zkvm/cuda"]
metal = ["risc0-zkvm/metal"]
