"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2023-06-24 18:46:24.820691

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collatz_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('input_value', sa.BigInteger(), nullable=True),
    sa.Column('output_sequence', postgresql.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('proof', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collatz_data_input_value'), 'collatz_data', ['input_value'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collatz_data_input_value'), table_name='collatz_data')
    op.drop_table('collatz_data')
    # ### end Alembic commands ###