[package]
name = "prorata-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
# If you want to try (experimental) std support, add `features = [ "std" ]` to risc0-zkvm
risc0-zkvm = { path = "../../../../risc0/zkvm", default-features = false, features = [
    "std",
] }
prorata-core = { path = "../../core", default-features = false, features = [
    "guest",
] }
bincode = "1.3.3"
rust_decimal = "1.29.1"
