[workspace]

[package]
name = "risc0-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkp = { path = "../zkp", default-features = false }
risc0-zkvm = { path = "../zkvm", default-features = false }
