[package]
name = "zkevm-core"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = { version = "1.1", default-features = false }
ethers-core = { version = "2.0", optional = true }
ethers-providers = { version = "2.0", optional = true }
futures = { version = "0.3", optional = true }
getrandom = { version = "0.2", features = ["custom"] }
primitive-types = { version = "0.12", features = ["serde"] }
revm = { version = "3.3", default-features = false, features = ["std", "serde"] }
serde = "1.0"
tokio = { version = "1.23", features = ["rt-multi-thread", "macros"], optional = true }

[features]
default = ["ethers"]
ethers = ["tokio", "ethers-providers", "ethers-core", "futures"]
