[workspace]
resolver = "2"
members = [
  "bonsai/sdk",
  "risc0/bootstrap",
  "risc0/bootstrap/poseidon",
  "risc0/build",
  "risc0/build_kernel",
  "risc0/cargo-risczero",
  "risc0/circuit/rv32im",
  "risc0/circuit/rv32im-sys",
  "risc0/core",
  "risc0/r0vm",
  "risc0/sys",
  "risc0/tools",
  "risc0/zkp",
  "risc0/zkvm",
  "risc0/zkvm/methods",
  "risc0/zkvm/platform",
]
exclude = [
  "tools/crates-validator"
]

[workspace.package]
version = "0.15.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[workspace.dependencies]
bonsai-sdk           = { version = "0.1.0", default-features = false, path = "bonsai/sdk" }
risc0-build          = { version = "0.15.0", default-features = false, path = "risc0/build" }
risc0-build-kernel   = { version = "0.15.0", default-features = false, path = "risc0/build_kernel" }
risc0-circuit-rv32im = { version = "0.15.0", default-features = false, path = "risc0/circuit/rv32im" }
risc0-circuit-rv32im-sys = { version = "0.15.0", default-features = false, path = "risc0/circuit/rv32im-sys" }
risc0-core           = { version = "0.15.0", default-features = false, path = "risc0/core" }
risc0-sys            = { version = "0.15.0", default-features = false, path = "risc0/sys" }
risc0-zkp            = { version = "0.15.0", default-features = false, path = "risc0/zkp" }
risc0-zkvm           = { version = "0.15.0", default-features = false, path = "risc0/zkvm" }
risc0-zkvm-platform  = { version = "0.15.0", default-features = false, path = "risc0/zkvm/platform" }

[profile.bench]
lto = true

# Always optimize; otherwise tests take excessively long.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3
