[package]
name = "risc0-zkvm"
description = "RISC Zero zero-knowledge VM"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[[bench]]
name = "fib"
harness = false

[[bench]]
name = "guest_run"
harness = false

[build-dependencies]
prost-build = { version = "0.11", optional = true }
protobuf-src = { version = "1.1", optional = true }

[dependencies]
anyhow = { version = "1.0", default-features = false }
bytemuck = { version = "1.13", features = ["extern_crate_alloc"] }
cfg-if = "1.0"
getrandom = { version = "0.2", features = ["custom"] }
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
libm = "0.2"
risc0-circuit-rv32im = { workspace = true }
risc0-core = { workspace = true }
risc0-zkp = { workspace = true }
risc0-zkvm-platform = { workspace = true }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
tracing = { version = "0.1", default-features = false, features = ["attributes"] }

# TODO(nils): Change these `target_os` checks to `target_vendor` checks when we
# have a real target triple.
#
# Host dependencies
[target.'cfg(not(target_os = "zkvm"))'.dependencies]
addr2line = { version = "0.20", optional = true }
bincode = { version = "1.3", optional = true }
elf = { version = "0.7", optional = true }
generic-array = { version = "0.14", default-features = false, optional = true }
getrandom = { version = "0.2", optional = true }
gimli = { version = "0.27", optional = true }
lazy-regex = { version = "2.3", optional = true }
log = "0.4"
crypto-bigint = { version = "0.5", default-features = false, features = ["rand"], optional = true }
num-derive = "0.3"
num-traits = { version = "0.2", default-features = false, optional = true }
prost = { version = "0.11", optional = true }
rand = { version = "0.8", optional = true }
rayon = { version = "1.5", optional = true }
rrs-lib = { version = "0.1", optional = true }
sha2 = { version = "0.10", optional = true }
typetag = { version = "0.2", optional = true }

[dev-dependencies]
clap = { version = "4.0", features = ["derive"] }
criterion = { version = "0.5", features = ["html_reports"] }
human-repr = "1.0"
tracing-forest = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[target.'cfg(not(target_os = "zkvm"))'.dev-dependencies]
env_logger = "0.10"
flate2 = "1.0"
risc0-zkvm-methods = { path = "methods" }
serial_test = "2.0"
tar = "0.4"
test-log = { version = "0.2", features = ["trace"] }

[features]
binfmt = ["dep:elf", "std"]
cuda = ["prove", "risc0-circuit-rv32im/cuda", "risc0-zkp/cuda"]
metal = ["prove", "risc0-circuit-rv32im/metal", "risc0-zkp/metal"]
default = ["prove"]
profiler = [
  "dep:addr2line",
  "dep:gimli",
  "dep:prost",
  "dep:prost-build",
  "dep:protobuf-src"
]
prove = [
  "binfmt",
  "dep:bincode",
  "dep:num-traits",
  "dep:generic-array",
  "dep:getrandom",
  "dep:lazy-regex",
  "dep:crypto-bigint",
  "dep:rand",
  "dep:rayon",
  "dep:rrs-lib",
  "dep:sha2",
  "dep:typetag",
  "risc0-circuit-rv32im/prove",
  "risc0-zkp/prove",
  "std",
]
std = [
  "anyhow/std",
  "num-traits?/std",
  "risc0-circuit-rv32im/std",
  "risc0-zkp/std",
  "serde/std",
]
