name: Benchmark Trends

on:
  push:
    branches: [ main ]
    # Only run benchmarks on changes to following paths:
    paths:
      - 'risc0/**'
      - '.github/workflows/bench_*'

  # uncomment for only for testing changes to this workflow while in a PR
  # pull_request:
  #   branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  bench:
    runs-on: [self-hosted, prod, bench, "${{ matrix.os }}", "${{ matrix.device }}"]

    strategy:
      fail-fast: false
      matrix:
        os: [Linux, macOS]
        feature: [default]
        device: [cpu]
        include:
          - os: Linux
            feature: cuda
            device: nvidia_rtx_a5000
          - os: macOS
            feature: metal
            device: apple_m2_pro

    env:
      CUDA_LIBRARY_PATH: /usr/lib/cuda
      FEATURE: ${{ matrix.feature }}
      RUSTC_WRAPPER: sccache

    steps:
      # This is a workaround from: https://github.com/actions/checkout/issues/590#issuecomment-970586842
      - run: "git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :"
      - uses: actions/checkout@v3
      - uses: ./.github/actions/rustup
      - uses: ./.github/actions/sccache
      - run: cargo bench -F $FEATURE --bench fib -- --output-format=bencher | tee output.txt
      - name: Store benchmark result
        uses: risc0/github-action-benchmark@risc0
        with:
          name: "${{ matrix.os }}-${{ matrix.device }}"
          tool: 'cargo'
          github-token: ${{ secrets.BENCHMARK_TOKEN }}
          gh-repository: 'github.com/risc0/ghpages'
          gh-repository-dir: '${{ runner.temp }}/benchmark-data-repository'
          gh-pages-branch: main
          output-file-path: output.txt
          comment-always: false
          comment-on-alert: false
          auto-push: true
