name: CI

on:
  push:
    branches: [ main, 'release-*' ]
  pull_request:
    branches: [ main, 'release-*' ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Full history is required by license-check.py
          fetch-depth: 0
      - uses: ./.github/actions/rustup
      - name: Install cargo-sort
        uses: risc0/cargo-install@2cfb0024938d23011106cbf127b393bc83fddba1
        with:
          crate: cargo-sort
          version: "1.0"
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cargo fmt --all --check
      - run: cargo fmt --all --check --manifest-path examples/Cargo.toml
      - run: cargo sort --workspace --check
      - run: cargo sort --workspace --check examples
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python license-check.py

  test:
    runs-on: [self-hosted, prod, "${{ matrix.os }}", "${{ matrix.device }}"]
    strategy:
      fail-fast: false
      matrix:
        os: [Linux, macOS]
        feature: [default]
        device: [cpu]
        include:
          - os: Linux
            feature: cuda
            device: nvidia_rtx_a5000
          - os: macOS
            feature: metal
            device: apple_m2_pro
          # - os: Linux
          #   feature: cuda
          #   device: nvidia_tesla_t4g
    env:
      CUDA_LIBRARY_PATH: /usr/lib/cuda
      FEATURE: ${{ matrix.feature }}
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache
    steps:
      # This is a workaround from: https://github.com/actions/checkout/issues/590#issuecomment-970586842
      - run: "git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :"
      - uses: actions/checkout@v3
      - uses: ./.github/actions/rustup
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: ./.github/actions/sccache
      - run: cargo test -F $FEATURE -F profiler
      - run: cargo test -F $FEATURE --tests -- --ignored
      - run: cargo test -F $FEATURE --manifest-path examples/Cargo.toml
      - run: cargo build --manifest-path risc0/wasm/Cargo.toml --target wasm32-unknown-unknown
        if: matrix.device == 'cpu'
      - run: cargo check -F $FEATURE --benches
      - run: cargo check -p bootstrap
        if: matrix.device == 'cpu'
      - run: cargo check -p risc0-build
        if: matrix.device == 'cpu'
      - run: cargo check -F $FEATURE -p risc0-circuit-rv32im
      - run: cargo check -p risc0-core
        if: matrix.device == 'cpu'
      - run: cargo check -F $FEATURE -p risc0-r0vm
      - run: cargo check -F $FEATURE -p risc0-sys
      - run: cargo check -F $FEATURE -p risc0-zkp
      - run: cargo check -F $FEATURE -p risc0-zkvm
      - run: sccache --show-stats

  doc:
    runs-on: [self-hosted, prod, Linux, cpu]
    steps:
      # This is a workaround from: https://github.com/actions/checkout/issues/590#issuecomment-970586842
      - run: "git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :"
      - uses: actions/checkout@v3
      - uses: ./.github/actions/rustup
      - uses: ./.github/actions/sccache
      - run: RISC0_SKIP_BUILD=1 cargo doc --no-deps --exclude=risc0-zkvm-methods --workspace
      - name: Install mdbook
        uses: risc0/cargo-install@2cfb0024938d23011106cbf127b393bc83fddba1
        with:
          crate: mdbook
          version: "0.4"
      - run: mdbook test
        working-directory: docs/mdbook

  check_template:
    runs-on: [self-hosted, prod, cpu, "${{ matrix.os }}"]
    strategy:
      fail-fast: false
      matrix:
        os: [Linux, macOS]

    steps:
      # This is a workaround from: https://github.com/actions/checkout/issues/590#issuecomment-970586842
      - run: "git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :"
      - uses: actions/checkout@v3
      - uses: ./.github/actions/rustup
      - run: |
          cargo run -p cargo-risczero risczero new --template templates/rust-starter --templ-subdir="" --path $(pwd) --dest ${{ runner.temp }} template-test
        shell: bash
      - run: cargo build --release --manifest-path ${{ runner.temp }}/template-test/Cargo.toml
      - run: ${{ runner.temp }}/template-test/target/release/host
